all: binary_search bubblesort heapsort insertionsort linear_search mergesort qsort selectionsort

CC=g++
CFLAGS=-Wall -c

binary_search.o: binary_search.cpp
	 $(CC) $(CFLAGS) binary_search.cpp

bubblesort.o: bubblesort.cpp
	 $(CC) $(CFLAGS) bubblesort.cpp

heapsort.o: heapsort.cpp
	 $(CC) $(CFLAGS) heapsort.cpp

insertionsort.o: insertionsort.cpp
	 $(CC) $(CFLAGS) insertionsort.cpp

linear_search.o: linear_search.cpp
	 $(CC) $(CFLAGS) linear_search.cpp

mergesort.o: mergesort.cpp
	 $(CC) $(CFLAGS) mergesort.cpp

qsort.o: qsort.cpp
	 $(CC) $(CFLAGS) qsort.cpp

selectionsort.o: selectionsort.cpp
	 $(CC) $(CFLAGS) selectionsort.cpp

clean:
	rm -f *.o binary_search bubblesort heapsort insertionsort linear_search mergesort qsort selectionsort
